run_fastqc: 1
trim_reads: 1
plot_bamstats: 1
#required for any step before population level genotyping. Deactivate this only if you have a finished VCF file and just want to filter it without snakemake looking for fastq files from the sample list
find_fastq_files: 1
#list of regular expression pairs used to identify PE read pairs. Pairs are separated with "," and forward and reverse REs of the same pair with ":". 
paired_end_res: ".*R1.*:.*R2.*,.*fwd.*:.*rev.*"
#additional options for trimmomatic
#Cut N bases at the beginning of the read. Standard value does nothing
trimmomatic_headcrop: 0
#Adapter clipping options
#specifies the maximum mismatch count which will still allow a full match to be performed
trimmomatic_clip_seedmismatches: 2
#specifies how accurate the match between the two 'adapter ligated' reads must be for PE palindrome read alignment.
trimmomatic_clip_palindromethresh: 30
#specifies how accurate the match between any adapter etc. sequence must be against a read.
trimmomatic_clip_simplethresh: 10
#Other trimming steps
#Remove leading below this quality
trimmomatic_trailing: 15
#Remove trailing below this quality
trimmomatic_leading: 15
#Width of sliding window
trimmomatic_slidingw_size: 4
#Cutting when the average quality per base drops below this
trimmomatic_slidingw_qual: 15
#Drop reads below this length
trimmomatic_minlen: 50

#default resources for rule trimmomatic
trimmomatic_mem_mb: 32000
trimmomatic_disk_mb: 4000
trimmomatic_runtime: "12h"
#default resources for rule map_reads
map_reads_mem_mb: 32000
map_reads_disk_mb: 4000
map_reads_runtime: "24h"
#default resources for rule merge_bams_deduplicate
merge_bams_mem_mb: 16000
merge_bams_disk_mb: 16000
merge_bams_runtime: "24h"

bam_depth_mem_mb: 16000
bam_depth_disk_mb: 32000
bam_depth_runtime: "12h"
pandepth_window_size: 1000
pandepth_min_q: 20
