hapcaller_minbaseq: 20
hapcaller_minmapq: 20 
#default resources for rule hapcallerSub
hapcallerSub_mem_mb: 32000
hapcallerSub_disk_mb: 10000
hapcallerSub_runtime: "24:00:00"
#default resources for rule GenomicsDBimportSub
GenomicsDBimportSub_mem_mb: 32000
GenomicsDBimportSub_disk_mb: 10000
GenomicsDBimportSub_runtime: "12:00:00"
