depthmask_n: 10
#default resources for rule GenotypeGenomicsDBSub
GenotypeGenomicsDBSub_mem_mb: 50000
GenotypeGenomicsDBSub_disk_mb: 50000
GenotypeGenomicsDBSub_runtime: "24:00:00"
#default resources for rule make_depth_mask
make_depth_mask_mem_mb: 32000
make_depth_mask_disk_mb: 40000
make_depth_mask_runtime: "24:00:00"
#default resources for rule MergeSubVCFsbcftools
MergeSubVCFsbcftools_mem_mb: 32000
MergeSubVCFsbcftools_disk_mb: 20000
MergeSubVCFsbcftools_runtime: "6:00:00"

